Add deskPage
Rinasik/flash-tasks pull request #5
Opened 2022-05-11 06:32 UTC by Rinasik

У Gate нужно типы прописать. Двойное сообщение при ошибочном создании desk еще не исправил. deskList чуток изменил дизайн для удобства.

2022-05-11 09:57 UTC, Rinasik commented
Interface Gate прописал. Множественное сообщение при ошибочном создании desk исправил. Добавил columnService. ColumnContainer принимает через пропсы column(насчет этого решения нужно еще подумать). На бэке нужно добавить связь для items и  column, чтобы items я отрисовывал сразу с columns

2022-05-11 10:30 UTC, pronix575 requested changes

2022-05-11 10:30 UTC, pronix575 commented on frontend/src/services/columnService/columnService.container.tsx
> +
Почему пустой pullRequest?

2022-05-11 10:30 UTC, pronix575 commented on frontend/src/services/columnService/columnService.types.ts
> +    color:string | undefined;
Если возможно undefined то через вопросик color?: string

2022-05-11 10:30 UTC, pronix575 commented on frontend/src/services/dashboardService/desksListService/components/DesksList/DesksList.tsx
> +            onClick={() => navigate(`/Desk/${item._id}`)}
Вообще нужно объявлять функцию в контейнере и передавать дальше,типа navigateToDesk

Но таких кейсов вообще не должно вроде быть, оборачивай в Link

2022-05-11 10:30 UTC, pronix575 commented on frontend/src/services/dashboardService/desksListService/components/DesksList/DesksList.types.ts
> +  navigate: NavigateFunction;
Не нужно

2022-05-11 10:30 UTC, pronix575 commented on frontend/src/services/deskService/components/DeskPage/DeskPage.tsx
> +                <ColumnContainer column={column}/>
Где проп key?

2022-05-11 10:30 UTC, pronix575 commented on frontend/src/services/deskService/deskService.models.ts
> +const getDeskFx = deskServiceDomain.createEffect<string | undefined, Desk>(
Че это за кейс где может быть не string, а undefined?

Убери

2022-05-11 10:30 UTC, pronix575 commented on frontend/src/services/deskService/deskService.relations.ts
> +  fn: (gateData: GetDeskProps) => gateData.deskId,
Вот тут добавляешь filter: Boolean,

2022-05-11 10:30 UTC, pronix575 commented on frontend/src/services/deskService/deskService.relations.ts
> +  clock: deskService.inputs.GetDesk.open,
.open.map(({deskId}) => deskId)

Хз что у тебя может и не deskId

2022-05-11 10:30 UTC, pronix575 commented on frontend/src/services/routerService/components/Router/Router.tsx
>              <Route path="*"  element={<Navigate to="/Dashboard" />} />
Ставь подобные роут ниже остальных

2022-05-12 18:42 UTC, pronix575 approved these changes

2022-05-12 18:42 UTC, merged